name: Check Rebase on PR Update

on:
  pull_request:
    types:
      - synchronize

jobs:
  check_rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get base branch
        id: get_base_branch
        run: echo "::set-output name=base_branch::$(jq -r '.base.ref' $GITHUB_EVENT_PATH)"

      - name: Get current branch
        id: get_current_branch
        run: echo "::set-output name=current_branch::$(jq -r '.head.ref' $GITHUB_EVENT_PATH)"

      - name: Fetch latest changes in base branch
        run: git fetch origin ${{ steps.get_base_branch.outputs.base_branch }}

      - name: Check if the current branch is rebased on the latest base branch
        run: |
          base_commit=$(git rev-parse origin/${{ steps.get_base_branch.outputs.base_branch }})
          current_commit=$(git rev-parse origin/${{ steps.get_current_branch.outputs.current_branch }})

          if [ "$base_commit" != "$current_commit" ]; then
            echo "error: Your branch is not rebased on the latest base branch. Please rebase your branch."
            exit 1
          else
            echo "success: Your branch is rebased on the latest base branch."
          fi
